- CHANGELOG.md
- README.md
- pubspec.yaml
> Version bump 0.1.2

- .github/workflows/flutter.yaml
- README.md
:green_heart: rename build workflow
> :pencil: add badges

- example/lib/main.dart
- lib/tooltip_widget.dart
Related issues: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/74, https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/27
> fix: overflow description text

- CHANGELOG.md
- lib/src/layout_overlays.dart
> :bug: #92 Showcase in ReorderableListView show at incorrect position

- CHANGELOG.md
- README.md
- example/lib/main.dart
- lib/src/custom_paint.dart
- lib/src/showcase.dart
✨ Closes #166 shapeBorder need to be more customisable
> :sparkles: Closes #166 shapeBorder need to be more customisable

- README.md
- removed Fluttery's flutter challenge video link as It is not available on youtube anymore.
> :sparkles: update readme file.

- lib/src/tooltip_widget.dart
Add constraints for tooltip widget
Fix alignment of arrow
> Fix tooltip widget

- CHANGELOG.md
- lib/src/layout_overlays.dart
Add condition for determine state is active
> Fix bug #150

- CHANGELOG.md
- README.md
- lib/src/showcase_widget.dart
✨ feature/previous_next_function_added
> ✨ feature/previous_next_function_added

- CHANGELOG.md
- README.md
Add note on autoscroll feature.
> :feature: update README.md.

- CHANGELOG.md
- lib/src/showcase.dart
- lib/src/showcase_widget.dart
Feature added that user can enable/disable overlay click
> ✨ #237, #240, #244 Disable overlayClick

- lib/src/showcase.dart
- lib/src/tooltip_widget.dart
Adds an ability to change border radius of tip's container.
> ToolTip BorderRadius setting support

- README.md
There are extra brackets that may confuse beginners
> Fix a minor error in Readme file

- .github/pull_request_template.md
- CHANGELOG.md
- 📚 `pull_request_template.md.` file updated with proper document
> docs: 📚 `pull_request_template.md` file updated 

- CHANGELOG.md
- CONTRIBUTING.md
- 📚 `CONTRIBUTING.md` file updated with proper document
> docs: 📚 `CONTRIBUTING.md` file updated

- lib/src/tooltip_widget.dart
> fix: :bug: Tooltip right position issue

- lib/src/tooltip_widget.dart
> fix: 🐛 logic update in `tooltip_widget.dart`

- CHANGELOG.md
> release: :bookmark: version bump 1.1.8 to 2.0.0

- CHANGELOG.md
- pubspec.yaml
> release: :bookmark: version bump 2.0.0 to 2.0.0+1

- .github/workflows/title-validation.yml
- CHANGELOG.md
- workflow for PR title validation
> chore: 👷workflow for PR title validation

- CHANGELOG.md
- README.md
- lib/src/showcase.dart
- lib/src/showcase_widget.dart
This PR will allow user to enable/disable showcase globally with one boolean check.
Closes #318
> feat: :sparkles: Enable/disable showcase globally

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- example/android/app/src/main/AndroidManifest.xml
- lib/src/showcase.dart
- lib/src/tooltip_widget.dart
- pubspec.yaml
Add padding to title and description in tool-tip and minor pull request template fix.
Closes #316
> feat: :sparkles: Add padding to title and description

- example/lib/detailscreen.dart
- lib/src/enum.dart
- lib/src/get_position.dart
- lib/src/layout_overlays.dart
- lib/src/shape_clipper.dart
- lib/src/showcase.dart
- lib/src/showcase_widget.dart
- lib/src/tooltip_widget.dart
Miscellaneous Changes
- Refactors code for better readability and better syntax.
- Adds missing license header in a file.
- Improve formatting.
- Improvements on some unnecessary repetitive method calls.
- Adds some TODOs for the core team to look into and update if required. I am open to discuss this!
> chore: cosmetic changes & code refactor

- CHANGELOG.md
> docs:  :bookmark: version bump 2.0.0+1 to 2.0.1

- CHANGELOG.md
- lib/src/showcase.dart
- pubspec.yaml
Replaced `SizedBox.shrink` with `Offstage` widget to show empty view.
Closes #335 
> fix: :bug: Flutter inspector makes screen grey

- CHANGELOG.md
> docs: :memo: Update CHANGELOG.md file for version 2.0.3.

- README.md
- Updated package preview link
> fix: 🩹 Fixed README.md

- CHANGELOG.md
- pubspec.yaml
- Upgrade max limit of dart sdk in`pubspec.yaml`.
> feat: :arrow_up: Dart SDK Upgrade

- CHANGELOG.md
- pubspec.yaml
> chore: :bookmark: version bump from 2.0.3 to 2.1.0

- README.md
- Switched to using raw github content url for package banner.
> docs: :books: Update README.md

- CHANGELOG.md
- README.md
- example/lib/detailscreen.dart
- example/lib/main.dart
- lib/src/showcase_widget.dart
> feat!: :boom: Remove builder widget (#400)

- CHANGELOG.md
- README.md
- lib/src/showcase.dart
- pubspec.yaml
> fix: :bug: Fixed Extra padding when add targetShapeBorder (#452)

- CHANGELOG.md
- lib/src/showcase.dart
- lib/src/tooltip_widget.dart
fix: 🐛 Fixed showcase.withWidget not showing issue
- showcase.withWidget was hiding when action widgets are not provided
Closes #493 
> fix: 🐛 Fixed showcase.withWidget not showing issue

- CHANGELOG.md
- README.md
- pubspec.yaml
> chore: :bookmark: Version Bump 4.0.1

- lib/src/enum.dart
- lib/src/tooltip/render_object_manager.dart
- lib/src/tooltip/render_position_delegate.dart
🩹 separated code of tooltip position delegate
> fix: 🩹 separated code of tooltip position delegate

- CHANGELOG.md
- lib/src/showcase_widget.dart
Marked `ShowCaseWidget` to be removed in v6.0.0
> chore: :heavy_minus_sign: Update deprecated `ShowCaseWidget` removal version

- CHANGELOG.md
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/settings.gradle
Fixed example app to run in flutter version 3.32.5
> fix: 🐛 Fixed example app to run in flutter version 3.32.5

- .github/workflows/web-example-release.yml
- Updates web example on github page for every new github release published.
> feat: :green_heart: Github Action for Web example release

- example/android/app/build.gradle
- example/android/app/src/debug/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/profile/AndroidManifest.xml
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/settings.gradle
Enable running android example with latest flutter version.
> chore: :rotating_light: Make example app runnable on Android
