SimformSolutionsPvtLtd/flutter_showcaseview

lib/showcase.dart

#6 Issue resolved
_`slideAnimationController.dispose();` called before `super.dispose()`

controller dispose called before super

---

lib/showcase.dart
lib/tooltip_widget.dart

This PR adds a contentPadding property to the TooltipWidget. It also adds it to the Showcase, and gets passed through. The default value remains `EdgeInsets.symmetric(vertical: 8)` just as it is set in the code right now, but it's not hardcoded. So it turns this:
Into this:
This is useful in scenarios where don't need to use your own widget, but you want your text to appear nicely to users.

Add optional contentPadding

---

CHANGELOG.md
lib/src/tooltip_widget.dart
pubspec.yaml

🐛 fixes #173 showArrow parameter not working

:bug: fixes #173 showArrow parameter not working

---

analysis_options.yaml
pubspec.yaml

- Replace deprecated `effective_dart` with `flutter_lints`.
- Add 2 lint rules.

User flutter lints and remove deprecated effective_dart lints.

---

lib/src/showcase.dart
lib/src/tooltip_widget.dart

Added `ShowcaseDecriptionAlignment` to `Showcase` in relation to this issue: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/253

Showcase description alignment

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/src/showcase.dart
lib/src/showcase_widget.dart
lib/src/tooltip_widget.dart

This PR consist changes of parameter names in Showcase and ShowcaseWidget class.
Showcase class parameter:
- shapeBorder -> targetShapeBorder
- radius -> targetBorderRadius
- contentPadding ->tooltipPadding
- showcaseBackgroundColor ->tooltipBackgroundColor
- overlayPadding -> targetPadding
- tipBorderRadius -> tooltipBorderRadius
ShowCaseWidget class parameter:
- autoPlayLockEnable -> enableAutoPlayLock
Some of the parameter of Showcase.withWidget() has been moved from parameter list to initializer list which are 
title, description, titleAlignment, descriptionAlignment, titleTextStyle, descTextStyle, tooltipBackgroudColor, textColor, tooltipBorderRadius, tooltipPadding
- [-] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant …

fix!: 💥Parameter changes of the `Showcase` and `ShowCaseWidget` class

---

README.md

docs: 📚 readme.md updated with property listing

---

lib/src/showcase.dart
lib/src/showcase_widget.dart

Added Documentation comments to `Showcase` and `ShowCaseWidget` class parameters

feat: ✨ Added documentation comments to `Showcase` and `ShowCaseWidget`

---

CHANGELOG.md
lib/src/showcase.dart

#348 showcaseview after upgrade to flutter 3.7.1 not disable target click
We have used `ignorePointer` widget to ignore the default gesture added in showcase view. in the code refactore PR #325 we have used `ignoring` flag in `ignorePointer` widget to determine if default gesture should be ignored or not but somehow when `ignoring` flag is false then `ignorePointer` widget send the gesture event to target widgets when this should not be the case. instead of using `ignoring` flag if we unwrap the targetwidget with ignorePointer widget solves the issue.
#346 Don't respond to any clicks in target 
#348 showcaseview after upgrade to flutter 3.7.1 not disable target click …

fix: :bug: #346 Don't respond to any clicks in target &

---

CHANGELOG.md
README.md
lib/src/showcase.dart
lib/src/tooltip_widget.dart

:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/148) Add feasibility to add `textDirection` of `title` and `description`.

feat: :sparkles: Add feasibility to add `textDirection` of `title` and `description`.

---

lib/src/showcase.dart

fixed child-constructor-invocation issue caused on  
>sdk: '>=2.19.3 <3.0.0' with flutter_lints: ^2.0.0.
As for the example code, it also marches the format.

fix: child-constructor-invocation

---

CHANGELOG.md
lib/src/get_position.dart

Reduced call for render object. Improved conditions.
None.

fix: :zap: Optimize `GetPosition` class

---

lib/src/showcase.dart

- Updated `IgnorePointer` to `AbsorbPointer` as ignore pointer is not blocking tap to descendants
- removed `FractionalTranslation` as it is not shifting tappable area and only shifting paint of widgets
- Made `size` and `shapeBorder` not nullable as we are assigning not null values to that constructor variable
- Updated default `offset` to `rectBound.topLeft`

fix: 🐛 Fixed target hit area

---

lib/src/showcase.dart
lib/src/showcase_widget.dart

- Added `isShowCaseCompleted` getter to check the showcase is completed or not
- If the showcase is already completed no need to further process the `_nextIfAny` function operations and we will stop execution of this function. This may happen if a user taps very fast and lots of time on the showcase barrier
Closes #389

fix: 🐛 Ignore extra `_nextIfAny` function operations as showcase maybe discarded at the time of next call

---

lib/src/showcase.dart

- Updated `IgnorePointer` from `AbsorbPointer` to send HitTest to targeted widget as `AbsorbPointer` cancel all type of user interaction and `IgnorePointer`only cancel it's closest child's interaction( in our case `GestureDetector` used on child) and passes it to below widget(in our case target widget)
Closes #388

fix: 🐛 Updated `IgnorePointer` from `AbsorbPointer` to send HitTest to targeted widget (#388)

---

CHANGELOG.md
lib/src/showcase.dart

- Improved `showCaseWidgetState` variable in `Showcase` class by removing getter as getter will compute that variable every time thus reducing performance
- Updated `CHANGELOG.md`

fix: ⚡ Improved `showCaseWidgetState` variable in `Showcase` class

---

CHANGELOG.md
README.md
lib/src/showcase.dart
lib/src/tooltip_widget.dart
lib/src/widget/tooltip_slide_transition.dart

Fixed ToolTip Slide Transition
- Added `toolTipSlideEndDistance` to define motion range for tooltip slide animation.
- Added the `ToolTipSlideTransition` widget and removed `SlideTransition` to fix the sliding range issue because before sliding range increased as child's size increased

fix: 🐛 Fixed ToolTip Slide Transition

---

CHANGELOG.md
analysis_options.yaml
lib/src/tooltip_widget.dart

- Suppressed `textScaleFactor` deprecated warning in `tooltip_widget.dart` and added TODO to replace it in future.
- Removed `avoid_returning_null` deprecated lint rule from `analysis_options.yaml`.

fix: :shirt: Suppress Text Scale Factor Warning

---

CHANGELOG.md
lib/src/layout_overlays.dart
lib/src/tooltip_widget.dart
pubspec.yaml

- Removed use of `Overlay.maybeOf` from layout_overlays.dart.
- Downgraded flutter_lints version in pubspec.yaml.
- Wrapped `WidgetsBinding.instance` with `ambiguate` in tooltip_widget.dart.
- Replaced `titleLarge` and `titleSmall` text theme with `headline6` and `subtitle2` in tooltip_widget.dart.
- Version bump 2.1.1.
Closes #425

fix: :ambulance: Dart 2.12 Version Compatibility

---

CHANGELOG.md
lib/src/showcase.dart

- Added `mounted` check in `addPostFrameCallback` under `recalculateRootWidgetSize` in `showcase.dart` as to ensure that the operation is only performed if the element is mounted.
Closes #428

fix: :bug: Fixed RecalculateRootWidgetSize null check issue.

---

CHANGELOG.md
example/android/app/build.gradle
lib/src/tooltip_widget.dart
pubspec.yaml

After Flutter SDK 3.22, removed deprecated text theme for headline6 and subtitle2. To fix this issue I follow migration guide from [here](https://docs.flutter.dev/release/breaking-changes/3-19-deprecations#texttheme).
#434 
Follow Migration Guide
[Flutter Release Notes 3.22]: https://docs.flutter.dev/release/release-notes/release-notes-3.22.0

fix: Text Style on Flutter 3.22

---

CHANGELOG.md
lib/src/showcase.dart
lib/src/showcase_widget.dart

fix: :bug: Fixed Null check operator used on a null value (#449)

---

CHANGELOG.md
README.md
lib/src/showcase.dart
lib/src/tooltip_widget.dart

feat: ✨Provided margin parameter to change margin of the tooltip (#475).

---

CHANGELOG.md
README.md
lib/src/showcase.dart
lib/src/tooltip_widget.dart

- Added `titleAlignment` and `descriptionAlignment` parameters to align title and description within the tooltip widget
- Renamed parameters `titleAlignment` to `titleTextAlign` and `descriptionAlignment` to `descriptionTextAlign`
Closes #457 

fix!: 🐛 Fixed TitleAlign Issue

---

lib/src/showcase_widget.dart

ShowCaseWidgetState initializes the `anchoredOverlayKey` in `initRootWidget` after the first frame was rendered (`WidgetsBinding.instance.addPostFrameCallback`). This means that the `Showcase` widget's `AnchoredOverlay` will initially have the `key` property set to null. 
This causes unwanted behavior since when the key is eventually updated in the `AnchoredOverlay`, it will cause its child to get disposed and completely rebuilt. In my case, the child I pass into the `Showcase` widget and (so the `AnchoredOverlay`) is animated and disposing the child breaks its animations. 
I suggest that the `anchoredOverlayKey` in the `ShowCaseWidgetState` is initialized directly in the `initState` or if there is some reason for it to be initialized after the first frame (which I do not believe so), …

fix: AnchoredOverlayKey key init

---

lib/src/layout_overlays.dart
lib/src/showcase_widget.dart

fix: 🐛 Handle null RenderBox in AnchoredOverlay and provide fallback values(#464)
This PR addresses a bug where AnchoredOverlay was causing crashes when RenderBox was null or not yet laid out.
Added null-safe checks for RenderBox in AnchoredOverlay.
Provided fallback values (Offset.zero and an empty Rect) for safe calculations.
Improved code readability with null-aware operators and comments.
Closes #464 

fix: 🐛 Handle null RenderBox in AnchoredOverlay and provide fallback values(#464)

---

CHANGELOG.md
README.md
lib/src/showcase.dart

feat: ✨Provided alignment parameter to adjust the auto scroll alignment property (#478).
Added a parameter `scrollAlignment` to adjust the auto scroll alignment property
Closes #478 

feat: ✨Provided alignment parameter to adjust the auto scroll alignment property (#478).

---

CHANGELOG.md
README.md
lib/src/showcase.dart

Added 'enableAutoScroll` to `showcase` to override showcaseWidget's `enableAutoScroll` behaviour

feat: ✨ Added `enableAutoScroll` to `showcase`

---

CHANGELOG.md
lib/src/showcase.dart

fix: 🐛 Fixed mounter issue inside the `_scrollIntoView` function
- Added mounted checks before setState in `_scrollIntoView` function

fix: 🐛 Fixed mounter issue inside the `_scrollIntoView` function

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/src/showcase_widget.dart

Added `onDismiss` callback in `ShowCaseWidget` which will trigger whenever `onDismiss` method is
called
Closes #500

feat: ✨Added on dismiss callback in showcase view widget (#500)

---

CHANGELOG.md
lib/src/showcase.dart
lib/src/tooltip_action_button_widget.dart
lib/src/tooltip_widget.dart

fix: 🐛 Fixed curser not changing to click mode issue
- When cursor is hovering over the default action widget it does not change to click mode 
Closes #503 

fix: 🐛 Fixed cursor not changing to click mode issue (#503)

---

CHANGELOG.md
lib/src/showcase.dart

Fixed timer not canceling when tapped on `TooltipActionButton`
- When autoplay is enabled, tapping on the TooltipActionButton will move to the next showcase without canceling the previous timer. This won't cause any issues until the user presses the previous button, at which point the old timer will end the showcase earlier than anticipated.
Closes #506 

fix: 🐛 Fixed timer not cancelling when tapped on `TooltipActionButton` (#506)

---

CHANGELOG.md
lib/src/showcase/showcase.dart
lib/src/showcase_widget.dart

- Added missing assertion in `Showcase.withWidget()`
- Removed Controller method assertion as they are not properly working on web
Closes #515 

fix: 🩹 Added missing assertions for `Showcase.withWidget()` (#515)

---

CHANGELOG.md
lib/src/showcase/showcase.dart
lib/src/showcase/showcase_controller.dart
lib/src/tooltip/animated_tooltip_layout.dart
lib/src/tooltip/render_animation_delegate.dart
lib/src/tooltip/render_position_delegate.dart
lib/src/tooltip/tooltip_widget.dart
lib/src/utils/constants.dart

- Added support for `toolTipMargin` in `Showcase.withWidget`
- Added `targetTooltipGap` for space between target and tooltip
Closes #520 and #521

feat: ✨ Added support for `toolTipMargin` in `Showcase.withWidget` and added `targetTooltipGap` for space between target and tooltip

---

README.md
example/lib/detailscreen.dart
lib/src/showcase/showcase_view.dart

Currently, the onFinish and onDismiss callbacks can only be defined when ShowcaseView is registered, which is often at a global level. This forces developers to handle showcase completion logic far from the widget that initiated it, leading to tightly coupled code and state management challenges.
This change introduces a listener pattern, allowing any widget to subscribe to showcase events dynamically.
- Added `addOnFinishCallback` and `removeOnFinishCallback` to allow for dynamic subscription to the showcase completion event.
- Added `addOnDismissCallback` and `removeOnDismissCallback` for the showcase dismissal event.
- Updated the core logic to iterate and invoke all registered listeners when a showcase is finished or dismissed, ensuring backward compatibility with the original global …

feat: Expose onFinish and onDismiss listeners
